from app.schemas.review_request import ReviewRequest
from app.schemas.review_response import ReviewResponse
from app.utils.logger import get_logger

logger = get_logger(__name__)


def generate_code_review(request: ReviewRequest) -> ReviewResponse:
    logger.info(f"Generating dummy code review for language: {request.language}")

    return ReviewResponse(
        status="success",
        language=request.language,
        summary="This is a dummy code review response. Groq integration will be added in the next phase.",
        issues=[
            "No actual AI analysis is performed yet.",
            "This response is used to test the API flow."
        ],
        improvements=[
            "Add AI based code review using Groq.",
            "Improve response formatting after AI integration."
        ],
        complexity_analysis="Complexity analysis will be generated by the AI model in the next phase.",
        security_notes=[
            "Security review will be added after Groq integration."
        ],
        model="dummy-review-service"
    )