import json
from typing import Any, Dict, List

from app.utils.logger import get_logger

logger = get_logger(__name__)


def _ensure_list(value: Any) -> List[str]:
    if isinstance(value, list):
        return [str(item) for item in value]

    if isinstance(value, str):
        return [value]

    return []


def format_ai_review_response(raw_response: str) -> Dict[str, Any]:
    """
    Converts raw Groq response text into a structured dictionary.

    If the AI returns valid JSON, it is parsed directly.
    If parsing fails, the raw response is safely returned inside summary.
    """

    logger.info("Formatting AI review response")

    if not raw_response or not raw_response.strip():
        logger.warning("Empty AI response received")

        return {
            "summary": "No response was generated by the AI model.",
            "issues": [],
            "improvements": [],
            "complexity_analysis": "Not available."
          
        }

    cleaned_response = raw_response.strip()

    try:
        parsed_response = json.loads(cleaned_response)

        return {
            "summary": str(parsed_response.get("summary", "")),
            "issues": _ensure_list(parsed_response.get("issues", [])),
            "improvements": _ensure_list(parsed_response.get("improvements", [])),
            "complexity_analysis": str(
                parsed_response.get("complexity_analysis", "Not available.")
            )
        
        }

    except json.JSONDecodeError:
        logger.warning("AI response was not valid JSON. Returning fallback response.")

        return {
            "summary": cleaned_response,
            "issues": [
                "The AI response could not be parsed into structured JSON."
            ],
            "improvements": [
                "Try reducing input code size or making the prompt more specific."
            ],
            "complexity_analysis": "Could not extract complexity analysis separately."
           
        }